#!/bin/bash

tableExcludePattern="(joined)"

function getJdbcProp
{
  name=$1
  cat $cfg | grep $name | sed -e 's|<property name=".*">\(.*\)</property>|\1|g'
}

function outputReveng
{
  # Output reveng xml
  printf '<?xml version="1.0" encoding="UTF-8"?>\n'
  printf '<!DOCTYPE hibernate-reverse-engineering PUBLIC\n'
  printf '		"-//Hibernate/Hibernate Reverse Engineering DTD 3.0//EN"\n'
  printf '		"http://hibernate.sourceforge.net/hibernate-reverse-engineering-3.0.dtd" >\n'
  printf '<hibernate-reverse-engineering>\n'
  printf '\n\t<!-- DO NOT EDIT BY HAND -->\n'
  printf '\t<!-- AUTOGENERATED BY "new-pojos.sh" -->\n\n'

  sql=`printf "mysql -q --user=%s --password=%s --host=%s" ${jdbcUser} ${jdbcPass} ${jdbcUrl}`
  printf "show tables in %s;" $jdbcSchema | ${sql} | egrep -v ${tableExcludePattern} | tail -n +2 | while read n ; do
    printf '\t<table-filter match-name="%s" />\n' $n
  done

  printf '\n'
  cat $revExtra
  printf '\n'

  printf '</hibernate-reverse-engineering>\n'
}

function outputConfig
{
  cat $cfgPro
  ls -1 $pojos | cut -f 1 -d . | while read c ; do
    printf '\t\t<mapping class="%s.%s" />\n' $package $c
  done
  cat $cfgEpi
}

function modifyPojos
{
  echo Modifying POJOs

  # Find any @Column annotation with length=65535 and change to 'TEXT' type
  # This is to workaround an issue with Hibernate's HBM2DDL tool
  # https://forum.hibernate.org/viewtopic.php?p=2393404
  sed -e 's/\(@Column.*\)length=65535\(.*\)/\1columnDefinition="TEXT"\2/g'          -i $pojos/*.java
	  
  # Add @Cache annotations with imports
  sed -e 's/^@Entity/\
import org.hibernate.annotations.Cache;\
import org.hibernate.annotations.CacheConcurrencyStrategy;\
@Entity\
@Cache(usage = CacheConcurrencyStrategy.READ_WRITE)/' \
		-i $pojos/*.java
    
}

cfg="etc/hibernate.cfg.xml"
rev="etc/hibernate.reveng.xml"
cfgPro="etc/cfg.prologue"
cfgEpi="etc/cfg.epilogue"
revExtra="etc/reveng.extra"
res="src/main/resources/hibernate.cfg.xml"
tres=`sed s/main/test/ <<<$res`
pojos="src/main/java/com/netshelter/ifbrands/data/entity"
package="com.netshelter.ifbrands.data.entity"

#Get JDBC credentials
jdbcUrl=`getJdbcProp "hibernate.connection.url" | cut -f 3 -d: | cut -c3-`
jdbcUser=`getJdbcProp "hibernate.connection.username"`
jdbcPass=`getJdbcProp "hibernate.connection.password"`
jdbcSchema=`getJdbcProp "hibernate.default_schema"`

if [ -z $jdbcUrl ] ; then echo "Cannot find jdbcUrl" ; fi
if [ -z $jdbcUser ] ; then echo "Cannot find jdbcUser" ; fi
if [ -z $jdbcPass ] ; then echo "Cannot find jdbcPass" ; fi
if [ -z $jdbcSchema ] ; then echo "Cannot find jdbcSchema" ; fi

printf "%s:%s@%s/%s\n" $jdbcUser $jdbcPass $jdbcUrl $jdbcSchema

# Make reveng.xml file
outputReveng | tee $rev

# Create & tweak pojos
ant make-pojos
modifyPojos

# Create runtime config
outputConfig  | tee $res

# Create debug config
cat $res | sed '/REMOVE_FOR_TEST/d' > $tres

# Install to local repo (if dependency to other project)
#mvn -DskipTests=true install
