parameters:
#    idealspoon_frontend.example.class: Idealspoon\FrontendBundle\Example

services:
#    idealspoon_frontend.example:
#        class: %idealspoon_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
