package com.netshelter.ifbrands.data.entity;
// Generated May 7, 2013 10:36:08 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbActionLog generated by hbm2java
 */
@Entity
@Table(name="ifb_action_log"
)
public class IfbActionLog  implements java.io.Serializable {


     private Integer actionLogId;
     private String actionType;
     private String objectType;
     private Integer objectId;
     private Integer userKey;
     private String textValue;
     private Date createTimestamp;

    public IfbActionLog() {
    }

	
    public IfbActionLog(String actionType, Date createTimestamp) {
        this.actionType = actionType;
        this.createTimestamp = createTimestamp;
    }
    public IfbActionLog(String actionType, String objectType, Integer objectId, Integer userKey, String textValue, Date createTimestamp) {
       this.actionType = actionType;
       this.objectType = objectType;
       this.objectId = objectId;
       this.userKey = userKey;
       this.textValue = textValue;
       this.createTimestamp = createTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="action_log_id", unique=true, nullable=false)
    public Integer getActionLogId() {
        return this.actionLogId;
    }
    
    public void setActionLogId(Integer actionLogId) {
        this.actionLogId = actionLogId;
    }

    
    @Column(name="action_type", nullable=false)
    public String getActionType() {
        return this.actionType;
    }
    
    public void setActionType(String actionType) {
        this.actionType = actionType;
    }

    
    @Column(name="object_type")
    public String getObjectType() {
        return this.objectType;
    }
    
    public void setObjectType(String objectType) {
        this.objectType = objectType;
    }

    
    @Column(name="object_id")
    public Integer getObjectId() {
        return this.objectId;
    }
    
    public void setObjectId(Integer objectId) {
        this.objectId = objectId;
    }

    
    @Column(name="user_key")
    public Integer getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(Integer userKey) {
        this.userKey = userKey;
    }

    
    @Column(name="text_value", length=8000)
    public String getTextValue() {
        return this.textValue;
    }
    
    public void setTextValue(String textValue) {
        this.textValue = textValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }




}


