package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbAdNetwork generated by hbm2java
 */
@Entity
@Table(name="ifb_ad_network"
    , uniqueConstraints = @UniqueConstraint(columnNames="ad_network_name") 
)
public class IfbAdNetwork  implements java.io.Serializable {


     private Integer adNetworkId;
     private String adNetworkName;
     private Date createTimestamp;

    public IfbAdNetwork() {
    }

    public IfbAdNetwork(String adNetworkName, Date createTimestamp) {
       this.adNetworkName = adNetworkName;
       this.createTimestamp = createTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ad_network_id", unique=true, nullable=false)
    public Integer getAdNetworkId() {
        return this.adNetworkId;
    }
    
    public void setAdNetworkId(Integer adNetworkId) {
        this.adNetworkId = adNetworkId;
    }

    
    @Column(name="ad_network_name", unique=true, nullable=false)
    public String getAdNetworkName() {
        return this.adNetworkName;
    }
    
    public void setAdNetworkName(String adNetworkName) {
        this.adNetworkName = adNetworkName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }




}


