package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbAdType generated by hbm2java
 */
@Entity
@Table(name="ifb_ad_type"
    , uniqueConstraints = @UniqueConstraint(columnNames="ad_type_name") 
)
public class IfbAdType  implements java.io.Serializable {


     private Integer adTypeId;
     private String adTypeName;
     private Date createTimestamp;
     private Set<IfbAd> ifbAds = new HashSet<IfbAd>(0);

    public IfbAdType() {
    }

	
    public IfbAdType(String adTypeName, Date createTimestamp) {
        this.adTypeName = adTypeName;
        this.createTimestamp = createTimestamp;
    }
    public IfbAdType(String adTypeName, Date createTimestamp, Set<IfbAd> ifbAds) {
       this.adTypeName = adTypeName;
       this.createTimestamp = createTimestamp;
       this.ifbAds = ifbAds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ad_type_id", unique=true, nullable=false)
    public Integer getAdTypeId() {
        return this.adTypeId;
    }
    
    public void setAdTypeId(Integer adTypeId) {
        this.adTypeId = adTypeId;
    }

    
    @Column(name="ad_type_name", unique=true, nullable=false)
    public String getAdTypeName() {
        return this.adTypeName;
    }
    
    public void setAdTypeName(String adTypeName) {
        this.adTypeName = adTypeName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbAdType")
    public Set<IfbAd> getIfbAds() {
        return this.ifbAds;
    }
    
    public void setIfbAds(Set<IfbAd> ifbAds) {
        this.ifbAds = ifbAds;
    }




}


