package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbAdSize generated by hbm2java
 */
@Entity
@Table(name="ifb_ad_size"
    , uniqueConstraints = @UniqueConstraint(columnNames="ad_size_name") 
)
public class IfbAdSize  implements java.io.Serializable {


     private Integer adSizeId;
     private String adSizeName;
     private int width;
     private int height;
     private Date createTimestamp;

    public IfbAdSize() {
    }

    public IfbAdSize(String adSizeName, int width, int height, Date createTimestamp) {
       this.adSizeName = adSizeName;
       this.width = width;
       this.height = height;
       this.createTimestamp = createTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ad_size_id", unique=true, nullable=false)
    public Integer getAdSizeId() {
        return this.adSizeId;
    }
    
    public void setAdSizeId(Integer adSizeId) {
        this.adSizeId = adSizeId;
    }

    
    @Column(name="ad_size_name", unique=true, nullable=false)
    public String getAdSizeName() {
        return this.adSizeName;
    }
    
    public void setAdSizeName(String adSizeName) {
        this.adSizeName = adSizeName;
    }

    
    @Column(name="width", nullable=false)
    public int getWidth() {
        return this.width;
    }
    
    public void setWidth(int width) {
        this.width = width;
    }

    
    @Column(name="height", nullable=false)
    public int getHeight() {
        return this.height;
    }
    
    public void setHeight(int height) {
        this.height = height;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }




}


