package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbAdStatus generated by hbm2java
 */
@Entity
@Table(name="ifb_ad_status"
    , uniqueConstraints = @UniqueConstraint(columnNames="ad_status_name") 
)
public class IfbAdStatus  implements java.io.Serializable {


     private Integer adStatusId;
     private String adStatusName;
     private Date createTimestamp;
     private Set<IfbAd> ifbAds = new HashSet<IfbAd>(0);

    public IfbAdStatus() {
    }

	
    public IfbAdStatus(String adStatusName, Date createTimestamp) {
        this.adStatusName = adStatusName;
        this.createTimestamp = createTimestamp;
    }
    public IfbAdStatus(String adStatusName, Date createTimestamp, Set<IfbAd> ifbAds) {
       this.adStatusName = adStatusName;
       this.createTimestamp = createTimestamp;
       this.ifbAds = ifbAds;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ad_status_id", unique=true, nullable=false)
    public Integer getAdStatusId() {
        return this.adStatusId;
    }
    
    public void setAdStatusId(Integer adStatusId) {
        this.adStatusId = adStatusId;
    }

    
    @Column(name="ad_status_name", unique=true, nullable=false)
    public String getAdStatusName() {
        return this.adStatusName;
    }
    
    public void setAdStatusName(String adStatusName) {
        this.adStatusName = adStatusName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbAdStatus")
    public Set<IfbAd> getIfbAds() {
        return this.ifbAds;
    }
    
    public void setIfbAds(Set<IfbAd> ifbAds) {
        this.ifbAds = ifbAds;
    }




}


