package com.netshelter.ifbrands.data.entity;
// Generated Jul 8, 2013 3:44:14 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbAd generated by hbm2java
 */
@Entity
@Table(name="ifb_ad"
    , uniqueConstraints = @UniqueConstraint(columnNames="ad_key") 
)
public class IfbAd  implements java.io.Serializable {


     private Integer adId;
     private IfbFeed ifbFeed;
     private IfbCampaign ifbCampaign;
     private IfbAdType ifbAdType;
     private IfbAdStatus ifbAdStatus;
     private IfbAdState ifbAdState;
     private Integer adNetworkId;
     private String adKey;
     private String adName;
     private int adSizeId;
     private Date createTimestamp;
     private Date startDate;
     private Date stopDate;
     private String templateKey;

    public IfbAd() {
    }

	
    public IfbAd(IfbFeed ifbFeed, IfbCampaign ifbCampaign, IfbAdType ifbAdType, IfbAdStatus ifbAdStatus, IfbAdState ifbAdState, String adKey, String adName, int adSizeId, Date createTimestamp, String templateKey) {
        this.ifbFeed = ifbFeed;
        this.ifbCampaign = ifbCampaign;
        this.ifbAdType = ifbAdType;
        this.ifbAdStatus = ifbAdStatus;
        this.ifbAdState = ifbAdState;
        this.adKey = adKey;
        this.adName = adName;
        this.adSizeId = adSizeId;
        this.createTimestamp = createTimestamp;
        this.templateKey = templateKey;
    }
    public IfbAd(IfbFeed ifbFeed, IfbCampaign ifbCampaign, IfbAdType ifbAdType, IfbAdStatus ifbAdStatus, IfbAdState ifbAdState, Integer adNetworkId, String adKey, String adName, int adSizeId, Date createTimestamp, Date startDate, Date stopDate, String templateKey) {
       this.ifbFeed = ifbFeed;
       this.ifbCampaign = ifbCampaign;
       this.ifbAdType = ifbAdType;
       this.ifbAdStatus = ifbAdStatus;
       this.ifbAdState = ifbAdState;
       this.adNetworkId = adNetworkId;
       this.adKey = adKey;
       this.adName = adName;
       this.adSizeId = adSizeId;
       this.createTimestamp = createTimestamp;
       this.startDate = startDate;
       this.stopDate = stopDate;
       this.templateKey = templateKey;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="ad_id", unique=true, nullable=false)
    public Integer getAdId() {
        return this.adId;
    }
    
    public void setAdId(Integer adId) {
        this.adId = adId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="feed_id", nullable=false)
    public IfbFeed getIfbFeed() {
        return this.ifbFeed;
    }
    
    public void setIfbFeed(IfbFeed ifbFeed) {
        this.ifbFeed = ifbFeed;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campaign_id", nullable=false)
    public IfbCampaign getIfbCampaign() {
        return this.ifbCampaign;
    }
    
    public void setIfbCampaign(IfbCampaign ifbCampaign) {
        this.ifbCampaign = ifbCampaign;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ad_type_id", nullable=false)
    public IfbAdType getIfbAdType() {
        return this.ifbAdType;
    }
    
    public void setIfbAdType(IfbAdType ifbAdType) {
        this.ifbAdType = ifbAdType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ad_status_id", nullable=false)
    public IfbAdStatus getIfbAdStatus() {
        return this.ifbAdStatus;
    }
    
    public void setIfbAdStatus(IfbAdStatus ifbAdStatus) {
        this.ifbAdStatus = ifbAdStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ad_state_id", nullable=false)
    public IfbAdState getIfbAdState() {
        return this.ifbAdState;
    }
    
    public void setIfbAdState(IfbAdState ifbAdState) {
        this.ifbAdState = ifbAdState;
    }

    
    @Column(name="ad_network_id")
    public Integer getAdNetworkId() {
        return this.adNetworkId;
    }
    
    public void setAdNetworkId(Integer adNetworkId) {
        this.adNetworkId = adNetworkId;
    }

    
    @Column(name="ad_key", unique=true, nullable=false)
    public String getAdKey() {
        return this.adKey;
    }
    
    public void setAdKey(String adKey) {
        this.adKey = adKey;
    }

    
    @Column(name="ad_name", nullable=false)
    public String getAdName() {
        return this.adName;
    }
    
    public void setAdName(String adName) {
        this.adName = adName;
    }

    
    @Column(name="ad_size_id", nullable=false)
    public int getAdSizeId() {
        return this.adSizeId;
    }
    
    public void setAdSizeId(int adSizeId) {
        this.adSizeId = adSizeId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="stop_date", length=10)
    public Date getStopDate() {
        return this.stopDate;
    }
    
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    
    @Column(name="template_key", nullable=true)
    public String getTemplateKey() {
        return this.templateKey;
    }
    
    public void setTemplateKey(String templateKey) {
        this.templateKey = templateKey;
    }




}


