package com.netshelter.ifbrands.data.entity;
// Generated Jul 8, 2013 9:53:39 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbCampaign generated by hbm2java
 */
@Entity
@Table(name="ifb_campaign"
    , uniqueConstraints = @UniqueConstraint(columnNames="campaign_key") 
)
public class IfbCampaign  implements java.io.Serializable {


     private Integer campaignId;
     private IfbCampaignStatus ifbCampaignStatus;
     private IfbCampaignType ifbCampaignType;
     private String campaignKey;
     private String campaignName;
     private String userKey;
     private String clientUserKey;
     private int dpBrandId;
     private Date startDate;
     private Date stopDate;
     private String keywords;
     private boolean campaignEnabled;
     private Date createTimestamp;
     private Integer feedId;
     private String productName;
     private String callToAction;
     private String logoLocation;
     private String productDestination;
     private String goal;
     private Set<IfbAd> ifbAds = new HashSet<IfbAd>(0);
     private Set<IfbStoryAmplification> ifbStoryAmplifications = new HashSet<IfbStoryAmplification>(0);

    public IfbCampaign() {
    }

	
    public IfbCampaign(IfbCampaignStatus ifbCampaignStatus, IfbCampaignType ifbCampaignType, String campaignKey, String campaignName, String userKey, int dpBrandId, Date startDate, Date stopDate, String keywords, boolean campaignEnabled, Date createTimestamp) {
        this.ifbCampaignStatus = ifbCampaignStatus;
        this.ifbCampaignType = ifbCampaignType;
        this.campaignKey = campaignKey;
        this.campaignName = campaignName;
        this.userKey = userKey;
        this.dpBrandId = dpBrandId;
        this.startDate = startDate;
        this.stopDate = stopDate;
        this.keywords = keywords;
        this.campaignEnabled = campaignEnabled;
        this.createTimestamp = createTimestamp;
    }
    public IfbCampaign(IfbCampaignStatus ifbCampaignStatus, IfbCampaignType ifbCampaignType, String campaignKey, String campaignName, String userKey, String clientUserKey, int dpBrandId, Date startDate, Date stopDate, String keywords, boolean campaignEnabled, Date createTimestamp, Integer feedId, String productName, String callToAction, String logoLocation, String productDestination, String goal, Set<IfbAd> ifbAds, Set<IfbStoryAmplification> ifbStoryAmplifications) {
       this.ifbCampaignStatus = ifbCampaignStatus;
       this.ifbCampaignType = ifbCampaignType;
       this.campaignKey = campaignKey;
       this.campaignName = campaignName;
       this.userKey = userKey;
       this.clientUserKey = clientUserKey;
       this.dpBrandId = dpBrandId;
       this.startDate = startDate;
       this.stopDate = stopDate;
       this.keywords = keywords;
       this.campaignEnabled = campaignEnabled;
       this.createTimestamp = createTimestamp;
       this.feedId = feedId;
       this.productName = productName;
       this.callToAction = callToAction;
       this.logoLocation = logoLocation;
       this.productDestination = productDestination;
       this.goal = goal;
       this.ifbAds = ifbAds;
       this.ifbStoryAmplifications = ifbStoryAmplifications;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="campaign_id", unique=true, nullable=false)
    public Integer getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(Integer campaignId) {
        this.campaignId = campaignId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campaign_status_id", nullable=false)
    public IfbCampaignStatus getIfbCampaignStatus() {
        return this.ifbCampaignStatus;
    }
    
    public void setIfbCampaignStatus(IfbCampaignStatus ifbCampaignStatus) {
        this.ifbCampaignStatus = ifbCampaignStatus;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campaign_type_id", nullable=false)
    public IfbCampaignType getIfbCampaignType() {
        return this.ifbCampaignType;
    }
    
    public void setIfbCampaignType(IfbCampaignType ifbCampaignType) {
        this.ifbCampaignType = ifbCampaignType;
    }

    
    @Column(name="campaign_key", unique=true, nullable=false)
    public String getCampaignKey() {
        return this.campaignKey;
    }
    
    public void setCampaignKey(String campaignKey) {
        this.campaignKey = campaignKey;
    }

    
    @Column(name="campaign_name", nullable=false)
    public String getCampaignName() {
        return this.campaignName;
    }
    
    public void setCampaignName(String campaignName) {
        this.campaignName = campaignName;
    }

    
    @Column(name="user_key", nullable=false)
    public String getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    
    @Column(name="client_user_key")
    public String getClientUserKey() {
        return this.clientUserKey;
    }
    
    public void setClientUserKey(String clientUserKey) {
        this.clientUserKey = clientUserKey;
    }

    
    @Column(name="dp_brand_id", nullable=false)
    public int getDpBrandId() {
        return this.dpBrandId;
    }
    
    public void setDpBrandId(int dpBrandId) {
        this.dpBrandId = dpBrandId;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="start_date", nullable=false, length=10)
    public Date getStartDate() {
        return this.startDate;
    }
    
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="stop_date", nullable=false, length=10)
    public Date getStopDate() {
        return this.stopDate;
    }
    
    public void setStopDate(Date stopDate) {
        this.stopDate = stopDate;
    }

    
    @Column(name="keywords", nullable=false, length=1024)
    public String getKeywords() {
        return this.keywords;
    }
    
    public void setKeywords(String keywords) {
        this.keywords = keywords;
    }

    
    @Column(name="campaign_enabled", nullable=false)
    public boolean isCampaignEnabled() {
        return this.campaignEnabled;
    }
    
    public void setCampaignEnabled(boolean campaignEnabled) {
        this.campaignEnabled = campaignEnabled;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    
    @Column(name="feed_id")
    public Integer getFeedId() {
        return this.feedId;
    }
    
    public void setFeedId(Integer feedId) {
        this.feedId = feedId;
    }

    
    @Column(name="product_name")
    public String getProductName() {
        return this.productName;
    }
    
    public void setProductName(String productName) {
        this.productName = productName;
    }

    
    @Column(name="call_to_action")
    public String getCallToAction() {
        return this.callToAction;
    }
    
    public void setCallToAction(String callToAction) {
        this.callToAction = callToAction;
    }

    
    @Column(name="logo_location", length=2048)
    public String getLogoLocation() {
        return this.logoLocation;
    }
    
    public void setLogoLocation(String logoLocation) {
        this.logoLocation = logoLocation;
    }

    
    @Column(name="product_destination", length=2048)
    public String getProductDestination() {
        return this.productDestination;
    }
    
    public void setProductDestination(String productDestination) {
        this.productDestination = productDestination;
    }

    
    @Column(name="goal", length=1024)
    public String getGoal() {
        return this.goal;
    }
    
    public void setGoal(String goal) {
        this.goal = goal;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbCampaign")
    public Set<IfbAd> getIfbAds() {
        return this.ifbAds;
    }
    
    public void setIfbAds(Set<IfbAd> ifbAds) {
        this.ifbAds = ifbAds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbCampaign")
    public Set<IfbStoryAmplification> getIfbStoryAmplifications() {
        return this.ifbStoryAmplifications;
    }
    
    public void setIfbStoryAmplifications(Set<IfbStoryAmplification> ifbStoryAmplifications) {
        this.ifbStoryAmplifications = ifbStoryAmplifications;
    }




}


