package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbCampaignType generated by hbm2java
 */
@Entity
@Table(name="ifb_campaign_type"
    , uniqueConstraints = @UniqueConstraint(columnNames="campaign_type_name") 
)
public class IfbCampaignType  implements java.io.Serializable {


     private Integer campaignTypeId;
     private String campaignTypeName;
     private Date createTimestamp;
     private Set<IfbCampaign> ifbCampaigns = new HashSet<IfbCampaign>(0);

    public IfbCampaignType() {
    }

	
    public IfbCampaignType(String campaignTypeName, Date createTimestamp) {
        this.campaignTypeName = campaignTypeName;
        this.createTimestamp = createTimestamp;
    }
    public IfbCampaignType(String campaignTypeName, Date createTimestamp, Set<IfbCampaign> ifbCampaigns) {
       this.campaignTypeName = campaignTypeName;
       this.createTimestamp = createTimestamp;
       this.ifbCampaigns = ifbCampaigns;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="campaign_type_id", unique=true, nullable=false)
    public Integer getCampaignTypeId() {
        return this.campaignTypeId;
    }
    
    public void setCampaignTypeId(Integer campaignTypeId) {
        this.campaignTypeId = campaignTypeId;
    }

    
    @Column(name="campaign_type_name", unique=true, nullable=false)
    public String getCampaignTypeName() {
        return this.campaignTypeName;
    }
    
    public void setCampaignTypeName(String campaignTypeName) {
        this.campaignTypeName = campaignTypeName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbCampaignType")
    public Set<IfbCampaign> getIfbCampaigns() {
        return this.ifbCampaigns;
    }
    
    public void setIfbCampaigns(Set<IfbCampaign> ifbCampaigns) {
        this.ifbCampaigns = ifbCampaigns;
    }




}


