package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbFeed generated by hbm2java
 */
@Entity
@Table(name="ifb_feed"
    , uniqueConstraints = @UniqueConstraint(columnNames="feed_key") 
)
public class IfbFeed  implements java.io.Serializable {


     private Integer feedId;
     private String ordering;
     private String feedKey;
     private String feedName;
     private Date lastModified;
     private Date createTimestamp;
     private Set<IfbAd> ifbAds = new HashSet<IfbAd>(0);
     private Set<IfbFeedStory> ifbFeedStories = new HashSet<IfbFeedStory>(0);

    public IfbFeed() {
    }

	
    public IfbFeed(String ordering, String feedKey, String feedName, Date lastModified, Date createTimestamp) {
        this.ordering = ordering;
        this.feedKey = feedKey;
        this.feedName = feedName;
        this.lastModified = lastModified;
        this.createTimestamp = createTimestamp;
    }
    public IfbFeed(String ordering, String feedKey, String feedName, Date lastModified, Date createTimestamp, Set<IfbAd> ifbAds, Set<IfbFeedStory> ifbFeedStories) {
       this.ordering = ordering;
       this.feedKey = feedKey;
       this.feedName = feedName;
       this.lastModified = lastModified;
       this.createTimestamp = createTimestamp;
       this.ifbAds = ifbAds;
       this.ifbFeedStories = ifbFeedStories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="feed_id", unique=true, nullable=false)
    public Integer getFeedId() {
        return this.feedId;
    }
    
    public void setFeedId(Integer feedId) {
        this.feedId = feedId;
    }
    
    @Column(name="ordering", nullable=false, length=8)
    public String getOrdering() {
        return this.ordering;
    }
    
    public void setOrdering(String ordering) {
        this.ordering = ordering;
    }

    
    @Column(name="feed_key", unique=true, nullable=false)
    public String getFeedKey() {
        return this.feedKey;
    }
    
    public void setFeedKey(String feedKey) {
        this.feedKey = feedKey;
    }

    
    @Column(name="feed_name", nullable=false)
    public String getFeedName() {
        return this.feedName;
    }
    
    public void setFeedName(String feedName) {
        this.feedName = feedName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_modified", nullable=false, length=19)
    public Date getLastModified() {
        return this.lastModified;
    }
    
    public void setLastModified(Date lastModified) {
        this.lastModified = lastModified;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbFeed")
    public Set<IfbAd> getIfbAds() {
        return this.ifbAds;
    }
    
    public void setIfbAds(Set<IfbAd> ifbAds) {
        this.ifbAds = ifbAds;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbFeed")
    public Set<IfbFeedStory> getIfbFeedStories() {
        return this.ifbFeedStories;
    }
    
    public void setIfbFeedStories(Set<IfbFeedStory> ifbFeedStories) {
        this.ifbFeedStories = ifbFeedStories;
    }




}


