package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbFeedStoryStatus generated by hbm2java
 */
@Entity
@Table(name="ifb_feed_story_status"
    , uniqueConstraints = @UniqueConstraint(columnNames="feed_story_status_name") 
)
public class IfbFeedStoryStatus  implements java.io.Serializable {


     private Integer feedStoryStatusId;
     private String feedStoryStatusName;
     private Date createTimestamp;
     private Set<IfbFeedStory> ifbFeedStories = new HashSet<IfbFeedStory>(0);

    public IfbFeedStoryStatus() {
    }

	
    public IfbFeedStoryStatus(String feedStoryStatusName, Date createTimestamp) {
        this.feedStoryStatusName = feedStoryStatusName;
        this.createTimestamp = createTimestamp;
    }
    public IfbFeedStoryStatus(String feedStoryStatusName, Date createTimestamp, Set<IfbFeedStory> ifbFeedStories) {
       this.feedStoryStatusName = feedStoryStatusName;
       this.createTimestamp = createTimestamp;
       this.ifbFeedStories = ifbFeedStories;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="feed_story_status_id", unique=true, nullable=false)
    public Integer getFeedStoryStatusId() {
        return this.feedStoryStatusId;
    }
    
    public void setFeedStoryStatusId(Integer feedStoryStatusId) {
        this.feedStoryStatusId = feedStoryStatusId;
    }

    
    @Column(name="feed_story_status_name", unique=true, nullable=false)
    public String getFeedStoryStatusName() {
        return this.feedStoryStatusName;
    }
    
    public void setFeedStoryStatusName(String feedStoryStatusName) {
        this.feedStoryStatusName = feedStoryStatusName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbFeedStoryStatus")
    public Set<IfbFeedStory> getIfbFeedStories() {
        return this.ifbFeedStories;
    }
    
    public void setIfbFeedStories(Set<IfbFeedStory> ifbFeedStories) {
        this.ifbFeedStories = ifbFeedStories;
    }




}


