package com.netshelter.ifbrands.data.entity;
// Generated Jun 25, 2013 10:56:13 AM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbNotes generated by hbm2java
 */
@Entity
@Table(name="ifb_notes"
)
public class IfbNotes  implements java.io.Serializable {


     private Integer notesId;
     private int campaignId;
     private String notesText;
     private int userKey;
     private Date createTimestamp;
     private Date updateTimestamp;

    public IfbNotes() {
    }

	
    public IfbNotes(int campaignId, int userKey, Date createTimestamp, Date updateTimestamp) {
        this.campaignId = campaignId;
        this.userKey = userKey;
        this.createTimestamp = createTimestamp;
        this.updateTimestamp = updateTimestamp;
    }
    public IfbNotes(int campaignId, String notesText, int userKey, Date createTimestamp, Date updateTimestamp) {
       this.campaignId = campaignId;
       this.notesText = notesText;
       this.userKey = userKey;
       this.createTimestamp = createTimestamp;
       this.updateTimestamp = updateTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="notes_id", unique=true, nullable=false)
    public Integer getNotesId() {
        return this.notesId;
    }
    
    public void setNotesId(Integer notesId) {
        this.notesId = notesId;
    }

    
    @Column(name="campaign_id", nullable=false)
    public int getCampaignId() {
        return this.campaignId;
    }
    
    public void setCampaignId(int campaignId) {
        this.campaignId = campaignId;
    }

    
    @Column(name="notes_text", length=65535)
    public String getNotesText() {
        return this.notesText;
    }
    
    public void setNotesText(String notesText) {
        this.notesText = notesText;
    }

    
    @Column(name="user_key", nullable=false)
    public int getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(int userKey) {
        this.userKey = userKey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_timestamp", nullable=false, length=19)
    public Date getUpdateTimestamp() {
        return this.updateTimestamp;
    }
    
    public void setUpdateTimestamp(Date updateTimestamp) {
        this.updateTimestamp = updateTimestamp;
    }




}


