package com.netshelter.ifbrands.data.entity;
// Generated Jun 17, 2013 3:44:27 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbSurveyResponseLog generated by hbm2java
 */
@Entity
@Table(name="ifb_survey_response_log"
)
public class IfbSurveyResponseLog  implements java.io.Serializable {


     private Integer surveyResponseLogId;
     private IfbSurveyAnswer ifbSurveyAnswer;
     private String campaignKey;
     private String adKey;
     private int storyId;
     private Date createTime;
     private String remoteIp;
     private String remoteUserAgent;
     private String site;

    public IfbSurveyResponseLog() {
    }

	
    public IfbSurveyResponseLog(IfbSurveyAnswer ifbSurveyAnswer, String campaignKey, String adKey, int storyId, Date createTime, String site) {
        this.ifbSurveyAnswer = ifbSurveyAnswer;
        this.campaignKey = campaignKey;
        this.adKey = adKey;
        this.storyId = storyId;
        this.createTime = createTime;
        this.site = site;
    }
    public IfbSurveyResponseLog(IfbSurveyAnswer ifbSurveyAnswer, String campaignKey, String adKey, int storyId, Date createTime, String remoteIp, String remoteUserAgent, String site) {
       this.ifbSurveyAnswer = ifbSurveyAnswer;
       this.campaignKey = campaignKey;
       this.adKey = adKey;
       this.storyId = storyId;
       this.createTime = createTime;
       this.remoteIp = remoteIp;
       this.remoteUserAgent = remoteUserAgent;
       this.site = site;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="survey_response_log_id", unique=true, nullable=false)
    public Integer getSurveyResponseLogId() {
        return this.surveyResponseLogId;
    }
    
    public void setSurveyResponseLogId(Integer surveyResponseLogId) {
        this.surveyResponseLogId = surveyResponseLogId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="survey_answer_id", nullable=false)
    public IfbSurveyAnswer getIfbSurveyAnswer() {
        return this.ifbSurveyAnswer;
    }
    
    public void setIfbSurveyAnswer(IfbSurveyAnswer ifbSurveyAnswer) {
        this.ifbSurveyAnswer = ifbSurveyAnswer;
    }

    
    @Column(name="campaign_key", nullable=false, length=64)
    public String getCampaignKey() {
        return this.campaignKey;
    }
    
    public void setCampaignKey(String campaignKey) {
        this.campaignKey = campaignKey;
    }

    
    @Column(name="ad_key", nullable=false, length=64)
    public String getAdKey() {
        return this.adKey;
    }
    
    public void setAdKey(String adKey) {
        this.adKey = adKey;
    }

    
    @Column(name="story_id", nullable=false)
    public int getStoryId() {
        return this.storyId;
    }
    
    public void setStoryId(int storyId) {
        this.storyId = storyId;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    
    @Column(name="remote_ip", length=100)
    public String getRemoteIp() {
        return this.remoteIp;
    }
    
    public void setRemoteIp(String remoteIp) {
        this.remoteIp = remoteIp;
    }

    
    @Column(name="remote_user_agent", length=2048)
    public String getRemoteUserAgent() {
        return this.remoteUserAgent;
    }
    
    public void setRemoteUserAgent(String remoteUserAgent) {
        this.remoteUserAgent = remoteUserAgent;
    }

    
    @Column(name="site", nullable=false, length=64)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }




}


