package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import org.codehaus.jackson.annotate.JsonIgnore;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbSurveyAnswer generated by hbm2java
 */
@Entity
@Table(name="ifb_survey_answer"
)
public class IfbSurveyAnswer  implements java.io.Serializable {


     private Integer surveyAnswerId;
     private String displayName;
     private Date createTime;
     private Set<IfbSurveyResponseLog> ifbSurveyResponseLogs = new HashSet<IfbSurveyResponseLog>(0);
     private Set<IfbSurveyResponse> ifbSurveyResponses = new HashSet<IfbSurveyResponse>(0);
     private Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers = new HashSet<IfbSurveyQuestionTypeAnswer>(0);

    public IfbSurveyAnswer() {
    }

	
    public IfbSurveyAnswer(String displayName, Date createTime) {
        this.displayName = displayName;
        this.createTime = createTime;
    }
    public IfbSurveyAnswer(String displayName, Date createTime, Set<IfbSurveyResponseLog> ifbSurveyResponseLogs, Set<IfbSurveyResponse> ifbSurveyResponses, Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers) {
       this.displayName = displayName;
       this.createTime = createTime;
       this.ifbSurveyResponseLogs = ifbSurveyResponseLogs;
       this.ifbSurveyResponses = ifbSurveyResponses;
       this.ifbSurveyQuestionTypeAnswers = ifbSurveyQuestionTypeAnswers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="survey_answer_id", unique=true, nullable=false)
    public Integer getSurveyAnswerId() {
        return this.surveyAnswerId;
    }
    
    public void setSurveyAnswerId(Integer surveyAnswerId) {
        this.surveyAnswerId = surveyAnswerId;
    }

    
    @Column(name="display_name", nullable=false, length=100)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbSurveyAnswer")
@JsonIgnore
    public Set<IfbSurveyResponseLog> getIfbSurveyResponseLogs() {
        return this.ifbSurveyResponseLogs;
    }
    
    public void setIfbSurveyResponseLogs(Set<IfbSurveyResponseLog> ifbSurveyResponseLogs) {
        this.ifbSurveyResponseLogs = ifbSurveyResponseLogs;
    }

@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbSurveyAnswer")
    public Set<IfbSurveyResponse> getIfbSurveyResponses() {
        return this.ifbSurveyResponses;
    }
    
    public void setIfbSurveyResponses(Set<IfbSurveyResponse> ifbSurveyResponses) {
        this.ifbSurveyResponses = ifbSurveyResponses;
    }

@JsonIgnore
@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbSurveyAnswer")
    public Set<IfbSurveyQuestionTypeAnswer> getIfbSurveyQuestionTypeAnswers() {
        return this.ifbSurveyQuestionTypeAnswers;
    }
    
    public void setIfbSurveyQuestionTypeAnswers(Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers) {
        this.ifbSurveyQuestionTypeAnswers = ifbSurveyQuestionTypeAnswers;
    }




}


