package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbSurveyQuestionType generated by hbm2java
 */
@Entity
@Table(name="ifb_survey_question_type"
)
public class IfbSurveyQuestionType  implements java.io.Serializable {


     private Integer surveyQuestionTypeId;
     private String displayName;
     private Date createTime;
     private Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers = new HashSet<IfbSurveyQuestionTypeAnswer>(0);

    public IfbSurveyQuestionType() {
    }

	
    public IfbSurveyQuestionType(String displayName, Date createTime) {
        this.displayName = displayName;
        this.createTime = createTime;
    }
    public IfbSurveyQuestionType(String displayName, Date createTime, Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers) {
       this.displayName = displayName;
       this.createTime = createTime;
       this.ifbSurveyQuestionTypeAnswers = ifbSurveyQuestionTypeAnswers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="survey_question_type_id", unique=true, nullable=false)
    public Integer getSurveyQuestionTypeId() {
        return this.surveyQuestionTypeId;
    }
    
    public void setSurveyQuestionTypeId(Integer surveyQuestionTypeId) {
        this.surveyQuestionTypeId = surveyQuestionTypeId;
    }

    
    @Column(name="display_name", nullable=false, length=100)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ifbSurveyQuestionType")
    public Set<IfbSurveyQuestionTypeAnswer> getIfbSurveyQuestionTypeAnswers() {
        return this.ifbSurveyQuestionTypeAnswers;
    }
    
    public void setIfbSurveyQuestionTypeAnswers(Set<IfbSurveyQuestionTypeAnswer> ifbSurveyQuestionTypeAnswers) {
        this.ifbSurveyQuestionTypeAnswers = ifbSurveyQuestionTypeAnswers;
    }




}


