package com.netshelter.ifbrands.data.entity;
// Generated Jun 17, 2013 3:44:27 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbSurveyResponse generated by hbm2java
 */
@Entity
@Table(name="ifb_survey_response"
)
public class IfbSurveyResponse  implements java.io.Serializable {


     private Integer surveyResponseId;
     private IfbSurveyAnswer ifbSurveyAnswer;
     private String campaignKey;
     private String adKey;
     private int storyId;
     private int countValue;
     private Date createTime;
     private Date lastUpdate;
     private String site;

    public IfbSurveyResponse() {
    }

    public IfbSurveyResponse(IfbSurveyAnswer ifbSurveyAnswer, String campaignKey, String adKey, int storyId, int countValue, Date createTime, Date lastUpdate, String site) {
       this.ifbSurveyAnswer = ifbSurveyAnswer;
       this.campaignKey = campaignKey;
       this.adKey = adKey;
       this.storyId = storyId;
       this.countValue = countValue;
       this.createTime = createTime;
       this.lastUpdate = lastUpdate;
       this.site = site;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="survey_response_id", unique=true, nullable=false)
    public Integer getSurveyResponseId() {
        return this.surveyResponseId;
    }
    
    public void setSurveyResponseId(Integer surveyResponseId) {
        this.surveyResponseId = surveyResponseId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="survey_answer_id", nullable=false)
    public IfbSurveyAnswer getIfbSurveyAnswer() {
        return this.ifbSurveyAnswer;
    }
    
    public void setIfbSurveyAnswer(IfbSurveyAnswer ifbSurveyAnswer) {
        this.ifbSurveyAnswer = ifbSurveyAnswer;
    }

    
    @Column(name="campaign_key", nullable=false, length=64)
    public String getCampaignKey() {
        return this.campaignKey;
    }
    
    public void setCampaignKey(String campaignKey) {
        this.campaignKey = campaignKey;
    }

    
    @Column(name="ad_key", nullable=false, length=64)
    public String getAdKey() {
        return this.adKey;
    }
    
    public void setAdKey(String adKey) {
        this.adKey = adKey;
    }

    
    @Column(name="story_id", nullable=false)
    public int getStoryId() {
        return this.storyId;
    }
    
    public void setStoryId(int storyId) {
        this.storyId = storyId;
    }

    
    @Column(name="count_value", nullable=false)
    public int getCountValue() {
        return this.countValue;
    }
    
    public void setCountValue(int countValue) {
        this.countValue = countValue;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_time", nullable=false, length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_update", nullable=false, length=19)
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    
    @Column(name="site", nullable=false, length=64)
    public String getSite() {
        return this.site;
    }
    
    public void setSite(String site) {
        this.site = site;
    }




}


