package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * IfbStoryAmplification generated by hbm2java
 */
@Entity
@Table(name="ifb_story_amplification"
    , uniqueConstraints = @UniqueConstraint(columnNames="short_url_key") 
)
public class IfbStoryAmplification  implements java.io.Serializable {


     private Integer storyAmplificationId;
     private IfbCampaign ifbCampaign;
     private String shortUrlKey;
     private int dpStoryId;
     private String userKey;
     private String type;
     private Date createdAmplification;
     private Date lastAmplification;

    public IfbStoryAmplification() {
    }

	
    public IfbStoryAmplification(String shortUrlKey, int dpStoryId, String userKey, String type, Date createdAmplification, Date lastAmplification) {
        this.shortUrlKey = shortUrlKey;
        this.dpStoryId = dpStoryId;
        this.userKey = userKey;
        this.type = type;
        this.createdAmplification = createdAmplification;
        this.lastAmplification = lastAmplification;
    }
    public IfbStoryAmplification(IfbCampaign ifbCampaign, String shortUrlKey, int dpStoryId, String userKey, String type, Date createdAmplification, Date lastAmplification) {
       this.ifbCampaign = ifbCampaign;
       this.shortUrlKey = shortUrlKey;
       this.dpStoryId = dpStoryId;
       this.userKey = userKey;
       this.type = type;
       this.createdAmplification = createdAmplification;
       this.lastAmplification = lastAmplification;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="story_amplification_id", unique=true, nullable=false)
    public Integer getStoryAmplificationId() {
        return this.storyAmplificationId;
    }
    
    public void setStoryAmplificationId(Integer storyAmplificationId) {
        this.storyAmplificationId = storyAmplificationId;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="campaign_id")
    public IfbCampaign getIfbCampaign() {
        return this.ifbCampaign;
    }
    
    public void setIfbCampaign(IfbCampaign ifbCampaign) {
        this.ifbCampaign = ifbCampaign;
    }

    
    @Column(name="short_url_key", unique=true, nullable=false, length=16)
    public String getShortUrlKey() {
        return this.shortUrlKey;
    }
    
    public void setShortUrlKey(String shortUrlKey) {
        this.shortUrlKey = shortUrlKey;
    }

    
    @Column(name="dp_story_id", nullable=false)
    public int getDpStoryId() {
        return this.dpStoryId;
    }
    
    public void setDpStoryId(int dpStoryId) {
        this.dpStoryId = dpStoryId;
    }

    
    @Column(name="user_key", nullable=false)
    public String getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    
    @Column(name="type", nullable=false, length=45)
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="created_amplification", nullable=false, length=19)
    public Date getCreatedAmplification() {
        return this.createdAmplification;
    }
    
    public void setCreatedAmplification(Date createdAmplification) {
        this.createdAmplification = createdAmplification;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_amplification", nullable=false, length=19)
    public Date getLastAmplification() {
        return this.lastAmplification;
    }
    
    public void setLastAmplification(Date lastAmplification) {
        this.lastAmplification = lastAmplification;
    }




}


