package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbUserValue generated by hbm2java
 */
@Entity
@Table(name="ifb_user_value"
)
public class IfbUserValue  implements java.io.Serializable {


     private Integer userValueId;
     private String userKey;
     private String keyName;
     private String value;
     private Date createTimestamp;

    public IfbUserValue() {
    }

    public IfbUserValue(String userKey, String keyName, String value, Date createTimestamp) {
       this.userKey = userKey;
       this.keyName = keyName;
       this.value = value;
       this.createTimestamp = createTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_value_id", unique=true, nullable=false)
    public Integer getUserValueId() {
        return this.userValueId;
    }
    
    public void setUserValueId(Integer userValueId) {
        this.userValueId = userValueId;
    }

    
    @Column(name="user_key", nullable=false)
    public String getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    
    @Column(name="key_name", nullable=false)
    public String getKeyName() {
        return this.keyName;
    }
    
    public void setKeyName(String keyName) {
        this.keyName = keyName;
    }

    
    @Column(name="value", nullable=false, length=2000)
    public String getValue() {
        return this.value;
    }
    
    public void setValue(String value) {
        this.value = value;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }




}


