package com.netshelter.ifbrands.data.entity;
// Generated Apr 12, 2013 12:26:23 PM by Hibernate Tools 3.2.4.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * IfbUserState generated by hbm2java
 */
@Entity
@Table(name="ifb_user_state"
)
public class IfbUserState  implements java.io.Serializable {


     private Integer userStateId;
     private int dpBrandId;
     private String userKey;
     private Date lastLogin;
     private Date createTimestamp;

    public IfbUserState() {
    }

    public IfbUserState(int dpBrandId, String userKey, Date lastLogin, Date createTimestamp) {
       this.dpBrandId = dpBrandId;
       this.userKey = userKey;
       this.lastLogin = lastLogin;
       this.createTimestamp = createTimestamp;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="user_state_id", unique=true, nullable=false)
    public Integer getUserStateId() {
        return this.userStateId;
    }
    
    public void setUserStateId(Integer userStateId) {
        this.userStateId = userStateId;
    }

    
    @Column(name="dp_brand_id", nullable=false)
    public int getDpBrandId() {
        return this.dpBrandId;
    }
    
    public void setDpBrandId(int dpBrandId) {
        this.dpBrandId = dpBrandId;
    }

    
    @Column(name="user_key", nullable=false)
    public String getUserKey() {
        return this.userKey;
    }
    
    public void setUserKey(String userKey) {
        this.userKey = userKey;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_login", nullable=false, length=19)
    public Date getLastLogin() {
        return this.lastLogin;
    }
    
    public void setLastLogin(Date lastLogin) {
        this.lastLogin = lastLogin;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_timestamp", nullable=false, length=19)
    public Date getCreateTimestamp() {
        return this.createTimestamp;
    }
    
    public void setCreateTimestamp(Date createTimestamp) {
        this.createTimestamp = createTimestamp;
    }




}


